package com.darkempire.anjifx.beans;

/**
 * Created with IntelliJ IDEA.
 * User: siredvin
 * Date: 23.09.13
 * Time: 21:57
 * To change this template use File | Settings | File Templates.
 */
public enum BeanType {
    STRING_TYPE, BOOLEAN_TYPE, DOUBLE_TYPE, INT_TYPE, CHOOSE_TYPE, LIST_TYPE, MAP_TYPE, TREE_TYPE, OBJECT_TYPE, POINT2D_TYPE, VECTOR2D_TYPE, COLOR_TYPE,
    LINEARGRADIEN_TYPE, RADIALGRADIENT_TYPE, FRACTION_TYPE, LONGFRACTION_TYPE, BIGFRACTION_TYPE, FUZZYBOOL_TYPE, LONG_TYPE, FLOAT_TYPE, POINT3D_TYPE, VECTOR3D_TYPE, COMPLEX_TYPE, FIXEDPOINT_TYPE, SET_TYPE, DOUBLEVECTOR_TYPE, ENUM_TYPE, LONG_BOUNDED_TYPE, DOUBLE_BOUNDED_TYPE, SQLDATE_TYPE, DATE_TYPE;

}
